config/routes.rb
Rails.application.routes.draw do

  root 'user#new'
  resources :user
end

app/models/user.rb
class User < ActiveRecord::Base
  require 'carrierwave/orm/activerecord'

  # mount_uploader :avatar, AvatarUploader

  validates :phone,  :presence => {:message => 'hello world, bad operation!'},
                     :numericality => true,
                     :length => { :minimum => 10, :maximum => 10 }
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true

  paginates_per 25

  scope :sort, -> { order(first_name: :asc, email: :asc) }
  scope :search, -> (query){
    where("first_name = ? or last_name = ? or email = ? or phone = ?", query, query, query, query)
  }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/user_controller.rb
class UserController < ApplicationController

  before_action :find_user, only: [:show, :destroy, :update]

  def index
    if params[:query]
      @users = User.where("first_name like '%#{params[:query]}%' or
                          last_name like '%#{params[:query]}%' or
                          email like '%#{params[:query]}%' or
                          phone like '%#{params[:query]}%'
                          ").sort.page params[:page]
    else
      @users = User.all.sort.page params[:page]
   end
  end

  def new
    @user = User.new
  end

  def create
    user = User.create(user_params)
    if user.save
      redirect_to user_index_path
    else
      flash[:error] = user.errors.messages
      redirect_to :back
    end
  end

  def update

    if @user.update_attributes(user_params)
      flash[:notice] = "Update success"
      redirect_to :back
    else
      flash[:error] = @user.errors.messages
      redirect_to :back
    end
  end

  def destroy
    if @user.destroy
      flash[:notice] = "Delete success"
      redirect_to :back
    end
  end

  private

  def find_user
    begin
      @user = User.find(params[:id])
    rescue
      redirect_to user_index_path
    end
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :phone)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DemoUserPage</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class="<%= controller_name %>-<%= action_name %> <%= params[:id].present? ? params[:id] : nil %>'">
  <nav class="navbar navbar-default">
    <div class="container-fluid">
      <div class="navbar-header">
        <%= link_to "All Users", user_index_path, class: "navbar-brand" %>
    </div>
  </nav>
  <% flash.each do |name, msg| -%>
    <% if name=='error' %>
      <div class="alert alert-danger row" role="alert">
        <%= content_tag :div, msg, class: "#{name} col-sm-12 text-center" %>
      </div>
    <% elsif name=='notice' %>
      <div class="alert alert-success row" role="alert">
        <%= content_tag :div, msg, class: "#{name} col-sm-12 text-center" %>
      </div>
    <% end %>
    <% end -%>
  <%= yield %>
</body>
</html>

app/views/user/index.html.erb
<div class="container">
  <div class="col-sm-12">
    <h2>Listing Users</h2>

    <%= form_tag request.path, method: :get, class: 'form-inline' do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], placeholder: "Typing search", class: 'form-control'%>
      </div>
      <%= submit_tag "Search", name: nil, class: 'btn btn-default' %>
    <% end %>

    <div class="pull-right" style="margin-top: -40px">
      <%= link_to "New Users", new_user_path, class: "btn btn-primary" %>
    </div>
  </div>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Firstname</th>
        <th>Email</th>
        <th>Details</th>
        <th>Delete</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each_with_index do |user , index| %>
        <tr>
          <th><%= index+1 %></th>
          <td><%= user.first_name %></td>
          <td><%= user.email %></td>
          <td>
            <%= link_to "View", user_path(user), class: "glyphicon glyphicon-inbox btn btn-sm btn-info" %>
          </td>
          <td>
            <%= link_to "Delete", user_path(user), class: "glyphicon glyphicon-remove btn btn-sm btn-danger", method: :delete, data: { confirm: "Do you want delete #{user.email}?"} %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="text-center col-sm-12">
    <%= paginate @users %>
  </div>

</div>

app/views/user/new.html.erb
<div class="span3 col-md-4 col-md-offset-4">
  <legend><h2>Create User</h2></legend>

  <%= form_for @user, url: user_index_path, method: :post do |f| %>
    <fieldset>
      <div class="form-group">
        <%= f.label :first_name, class: :"col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.text_field :first_name, class: :"form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :last_name, class: :"col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.text_field :last_name, class: :"form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, class: :"col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.email_field :email, class: :"form-control" %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :phone, class: :"col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <%= f.telephone_field :phone, class: :"form-control" %>
        </div>
      </div>

      <!-- <div class="form-group">
        <%= f.label :avatar, class: :"col-sm-4 control-label"  %>
        <div class="col-sm-8">
          <div class="col-sm-8"><%= f.file_field :avatar %></div>
        </div>
      </div> -->


      <div class="form-group">
        <div class="col-sm-12">
          <%= f.submit "Create", class: :"btn btn-primary col-sm-12"%>
        </div>
      </div>
    </fieldset>
  <% end %>
</div>

app/views/user/show.html.erb
<div class="container">
  <div class="panel panel-primary">
  <!-- Default panel contents -->
  <div class="panel-heading">
    <%= @user.email %>
    <div class="pull-right" style="margin-top: -5px">
      <%= link_to "", user_path(@user), class: "glyphicon glyphicon-remove btn btn-sm btn-danger", method: :delete, data: { confirm: "Do you want delete #{@user.email}?"} %>
    </div>
  </div>
  <div class="panel-body">
    <%= form_for @user, url: user_path(@user), method: :patch, html: { class: 'form-horizontal' } do |f| %>
      <fieldset>
        <div class='form-group'>
          <%= f.label :email, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
        </div>

        <div class='form-group'>
          <%= f.label :first_name, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :first_name, class: 'form-control' %>
          </div>
        </div>

        <div class='form-group'>
          <%= f.label :last_name, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :last_name, class: 'form-control' %>
          </div>
        </div>

        <div class='form-group'>
          <%= f.label :phone, class: 'col-sm-2 control-label' %>
          <div class='col-sm-10'>
            <%= f.text_field :phone, class: 'form-control' %>
          </div>
        </div>

        <div class='form-group'>
          <div class='col-sm-10 col-sm-offset-2'>
            <%= f.submit "Save", class: 'btn btn-success form-control' %>
          </div>
        </div>
      </fieldset>
    <% end %>
  </div>
</div>